[이창섭] Assignment 1: Express API - 초기 환경 세팅
wecode-bootcamp-korea/43-backend-westagram-3 pull request #1
Opened 2023-02-21 10:26 UTC by Chang9601

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- 환경 설정 및 초기화

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- westagram 개발을 위한 Express 초기 환경 설정 및 DB 연결

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- Express, nodemon, cors, Dotenv, Morgan, TypeORM 패키지 설치 및 적용
- dotenv의 경우 .env 파일에 DB 연결에 필요한 환경 변수 정의
- TypeORM 패키지를 통해서 westagram 데이터베이스 연결

<br />

## :: 테스트 결과 이미지
![DB connection](https://user-images.githubusercontent.com/79137839/220318481-ac3f359f-f5be-4423-972d-1da4dfae916c.png)

<br />

## :: 기타 질문 및 특이 사항
- 없음

2023-02-21 12:58 UTC, kyeongraekim requested changes

2023-02-21 12:58 UTC, kyeongraekim commented on changseob/app.js
> +const myDataSource = new DataSource({
- myDataSource 보다는 appDataSource , mysqlDataSource 혹은 간결하게 database로 변수명을 변경해주세요. “my”라는 용어는 예제 코드에서는 사용할 수 있으나 실제 코드에서는 피해주세요.

2023-02-21 12:58 UTC, kyeongraekim commented on changseob/app.js
> +myDataSource.initialize().then(() => {
- 추가로 DataSource.initialize() 함수가 실행되고 나면, then()과 catch()를 사용해서 에러를 핸들링해줄 수 있습니다. 이렇게 하면, initialize() 함수가 실행되어서 database와 실제로 connection을 생성할 때, 성공했는지 실패했는지 여부를 확인할 수 있습니다.

2023-02-21 12:58 UTC, kyeongraekim commented on changseob/app.js
> +
- import 순서 컨벤션에 맞게 수정해주세요! 사소한 부분이라 놓치기 쉽지만 처음 코드를 작성할 때부터 신경쓰고 작성하게 되면 추후에 관리하기도 용이하며 가독성도 좋아집니다.
- 다음과 같은 순서로 import 해줍니다.
        - Bulit-in 패키지
        - 3rd-party 패키지
        - custom 패키지
        
        ```javascript
        //// Built-in package
        const http = require('http')
        
        //// 3rd-party package
        require('dotenv').config();
        const express = require('express');
        const cors    = require('cors');
        const morgan  = require('morgan');
        const { DataSource } = require('typeorm');
        
        //custom package
        const api = require('./../api')
        
        const app = express();
        ```

2023-02-21 12:58 UTC, kyeongraekim commented on changseob/package.json
> +  }
- 프로젝트에서 3rd-party 패키지를 설치해서 사용할 때에는 주의해야 될 사항이 있습니다.
- 해당 패키지가 production 레벨(사용자에게 배포)에서 사용될 패키지인지 local 개발용도로만 사용되는 패키지인지를 알고 있어야 합니다.
- express, mysql, typeorm, dotenv, cors와 같은 패키지는 사용자에게 서비스되는 코드에서는 반드시 포함되어야 하는 라이브러리이므로 package.json 내에 `dependencies`에 포함되어야 합니다.
- 하지만, nodemon과 같은 패키지는 로컬에서 개발할 때, 생산성을 위해서 사용하는 패키지입니다. 그렇기 때문에 이는 `devDependencies`에 추가 혹은 `global 환경`에 설치해서 사용할 수 있도록 만들어주세요.

2023-02-21 12:58 UTC, kyeongraekim commented on changseob/app.js
> +const dotenv = require("dotenv");
- .env.sample 파일이 함께 올라와 있지 않네요!

2023-02-22 05:04 UTC, kyeongraekim requested changes
아래 마이너한 사항만 한번 수정해주세요!~

2023-02-22 05:04 UTC, kyeongraekim commented on changseob/.env.sample
> +TYPEORM_LOGGING=TRUE
- 현재 TYPEORM_CONNECTION 등의 환경변수 네이밍은 언제 어디든지 typeORM을 제외한 다양한 ORM 라이브러리와 연동될 수 있는 mysql의 환경 변수 용례를 극히 제한하는 모습처럼 보여집니다.
- 따라서 DB_CONNECTION, DB_HOST 등의 워딩으로 바꿔주시면 더 좋을 것 같아보입니다!
- 또한 환경변수의 밸류값은 샘플링을 위한 데이터임으로, 가장 포괄적인 내용으로 바꾸어주세요! chang, library는 실제 사용할 수 있을법한 혹은 과거에 사용했을법한 이름들이네요!

2023-02-22 05:26 UTC, Chang9601 commented on changseob/.env.sample
> +TYPEORM_LOGGING=TRUE
알겠습니다!

2023-02-22 07:41 UTC, kyeongraekim approved these changes
LGTM!~

2023-02-22 07:42 UTC, merged