[이창섭] Assignment 2: Express API - 유저 회원가입 하기
wecode-bootcamp-korea/43-backend-westagram-3 pull request #2
Opened 2023-02-21 12:53 UTC by Chang9601

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- 기능 추가
<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 유저 회원가입 (name, email, profile_image, password)

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- HTTP 메서드는 POST, 호출 URL은 users로 설정
- HTTP 응답 코드는 201, 응답 바디는 userCreated 반환
- 이름, 이메일, 배경사진, 비밀번호를 받아서 DB에 삽입

<br />

## :: 테스트 결과 이미지
![signup-postman](https://user-images.githubusercontent.com/79137839/220348879-521441bf-620d-4bac-9bb6-8f002225e391.png)
![signup-db](https://user-images.githubusercontent.com/79137839/220348886-de3f8394-f4b2-44d2-a49b-c9e8b42017e3.png)

<br />

## :: 기타 질문 및 특이 사항
- modularizedFunctions.js 파일에 app.js 파일에서 module.exports로 내보낸 TypeORM의 DataSource를 사용해서  회원가입 함수를 따로 구현할 경우  코드를 작성하면 똑같이 작동하나요?

2023-02-22 05:04 UTC, kyeongraekim commented
해당 내용은 과제 1번 머지후에 진행하도록 하겠습니다!~

2023-02-22 08:43 UTC, Chang9601 commented
머지는 완료했습니다!

2023-02-22 10:23 UTC, kyeongraekim requested changes
- app.js에 이전 리뷰를 반영한 버전으로 브랜치를 잘 머지시킨후 재 푸시해주세요!
- 그리고 db 폴더 내부에 migrations 파일은 깃헙에 함께 공유해주셔야 하는 코드입니다. schema.sql을 안올라오고, 해당 마이그레이션 파일들은 꼭 올라 올 수 있게 수정해주세요!

2023-02-23 01:30 UTC, kyeongraekim requested changes

2023-02-23 01:30 UTC, kyeongraekim commented on changseob/db/migrations/20230221103813_create_users_table.sql
> +  primary key (id)
- SQL의 컨벤션상 모든 것을 소문자로 해도 상관은 없지만, 가독성과 시인성을 위해서 컬럼명 등을 제외한 SQL 문법언어는 대문자로 변경하여 작성하는 케이스가 많이있습니다.
- 해당 내용에 대해 수정을 고려해보시고, 읽어볼만한 영어 발췌글을 다음과 같이 공유해드릴게요! [링크바로가기](https://dataschool.com/how-to-teach-people-sql/syntax-conventions/#:~:text=For%20readability%2C%20all%20SQL%20commands,what%20the%20query%20is%20executing.)

2023-02-23 01:30 UTC, kyeongraekim commented on changseob/db/migrations/20230221103823_create_likes_table.sql
> +);
- 좋아요 기능을 구현할 때에는 주의해야할 점이 있습니다.
- 하나의 사용자가 하나의 게시물에 대해서 좋아요를 할 수 있는 횟수는 단 한 번 이어야 합니다.
- 지금 구조에서는 좋아요를 누를 때마다 아래와 같이 likes 테이블에 계속해서 중복으로 데이터가 저장됩니다.
    
    ```sql
    +----+---------+---------+---------------------+
    | id | user_id | post_id | created_at          |
    +----+---------+---------+---------------------+
    |  1 |       1 |       3 | 2022-07-16 14:18:26 |
    |  2 |       1 |       3 | 2022-07-16 14:18:26 |
    |  3 |       1 |       3 | 2022-07-16 14:18:26 |
    |  4 |       1 |       3 | 2022-07-16 14:18:26 |
    |  5 |       1 |       3 | 2022-07-16 14:18:47 |
    |  6 |       1 |       3 | 2022-07-16 14:18:47 |
    +----+---------+---------+---------------------+
    ```
    
- 이를 막기 위해서, likes 테이블에 user_id와 post_id를 기준으로 UNIQUE 제약조건을 추가하는 migration 파일을 추가로 만들어서 올려주세요.

2023-02-23 07:56 UTC, kyeongraekim requested changes

2023-02-23 07:56 UTC, kyeongraekim commented on changseob/db/migrations/20230221103813_create_users_table.sql
> +  email VARCHAR(200) NOT NULL,
- 중복 이메일 가입을 막기 위해서 이메일 관련 unique 설정을 추가해주세요!~

2023-02-23 08:13 UTC, kyeongraekim approved these changes
LGTM!~

2023-02-23 08:13 UTC, merged