[문선정]Assignment 1: Experess API-initial setting
wecode-bootcamp-korea/43-backend-westagram-3 pull request #3
Opened 2023-02-22 09:54 UTC by tjswjd0218

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- express API 초기 세팅

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- express 환경 세팅
- TypeORM 환경 변수 설정
- 런서버 작동
- (DB migrations는 아직 영상 보면서 연습중)

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
![스크린샷 2023-02-22 오후 6 51 42(2)](https://user-images.githubusercontent.com/40467370/220585251-7cad38f6-39f9-4158-9ec8-c1cc5d516be9.png)

2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
<img width="1512" alt="스크린샷 2023-02-22 오후 6 52 01" src="https://user-images.githubusercontent.com/40467370/220585283-01ac4b5a-2d40-4fd5-9cf7-a7cfa85717e4.png">

3. [](url)

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-02-22 10:30 UTC, kyeongraekim requested changes

2023-02-22 10:30 UTC, kyeongraekim commented on seonjeong/app.js
> +const myDataSource = new DataSource({
- myDataSource 보다는 appDataSource , mysqlDataSource 혹은 간결하게 database로 변수명을 변경해주세요. “my”라는 용어는 예제 코드에서는 사용할 수 있으나 실제 코드에서는 피해주세요.

2023-02-22 10:30 UTC, kyeongraekim commented on seonjeong/app.js
> +    database: process.env.TYPEORM_DATABASE
- 현재 TYPEORM_CONNECTION 등의 환경변수 네이밍은 언제 어디든지 typeORM을 제외한 다양한 ORM 라이브러리와 연동될 수 있는 mysql의 환경 변수 용례를 극히 제한하는 모습처럼 보여집니다.
- 따라서 DB_CONNECTION, DB_HOST 등의 워딩으로 바꿔주시면 더 좋을 것 같아보입니다!
- 또한 환경변수의 밸류값은 샘플링을 위한 데이터임으로, 가장 포괄적인 내용으로 바꾸어주세요! chang, library는 실제 사용할 수 있을법한 혹은 과거에 사용했을법한 이름들이네요!

2023-02-22 10:30 UTC, kyeongraekim commented on seonjeong/app.js
> +dotenv.config()
- import 순서 컨벤션에 맞게 수정해주세요! 사소한 부분이라 놓치기 쉽지만 처음 코드를 작성할 때부터 신경쓰고 작성하게 되면 추후에 관리하기도 용이하며 가독성도 좋아집니다.

- 다음과 같은 순서로 import 해줍니다.
Bulit-in 패키지
3rd-party 패키지
custom 패키지

  ```javascript
  //// Built-in package
  const http = require('http')
  
  //// 3rd-party package
  require('dotenv').config();
  const express = require('express');
  const cors    = require('cors');
  const morgan  = require('morgan');
  const { DataSource } = require('typeorm');
  
  //custom package
  const api = require('./../api')
  
  const app = express();
  ```

2023-02-22 10:30 UTC, kyeongraekim commented on seonjeong/db/migrations/20230222062923_create_books_table.sql
> +CREATE TABLE books (
- 해당 내용은 동영상 예제로 쓰이는 책과 관련된 테이블이네요! Westagram 관련 테이블로 추후에 바꿔서 재푸시해주세요!

2023-02-23 07:55 UTC, kyeongraekim requested changes

2023-02-23 07:55 UTC, kyeongraekim commented on seonjeong/app.js
> +
불필요한 공백이 너무 많아 보이네요!~ 해당 부분만 간단히 수정하고 재푸시해주세요!~

2023-02-23 09:03 UTC, tjswjd0218 commented on seonjeong/app.js
> +
수정 후 저장/푸시 했는데 commit에서 확인하면 공백이 그대로 있고  Files changed 에서는 공백이 보이지 않습니다. 
반영 안된거면 다시 한번만 말씀해주세요..!

2023-02-24 01:36 UTC, kyeongraekim approved these changes
LGTM!~

2023-02-24 01:36 UTC, merged